title: Default
sections:
  main:
    display: Main
    fields:
      title:
        type: text
      content:
        type: markdown
        localizable: true
  sidebar:
    display: Sidebar
    fields:
      slug:
        type: text
